services:

  app:
    build: .
    container_name: projetphp_livrable_epsi_apache_prod
    ports:
      - "1919:80"
    environment:
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-Europe/Paris}
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-512M}
      PHP_UPLOAD_MAX_FILESIZE: ${PHP_UPLOAD_MAX_FILESIZE:-50M}
      PHP_POST_MAX_SIZE: ${PHP_POST_MAX_SIZE:-50M}
      DATABASE_HOST: ${DATABASE_HOST:-db}
      DATABASE_NAME: ${DATABASE_NAME:-projetphp_livrable_epsi_bdd}
      DATABASE_USER: ${DATABASE_USER:-projetphp_livrable_epsi}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - db
    restart: always

  db:
    image: mariadb:latest
    container_name: projetphp_livrable_epsi_bdd_prod
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MARIADB_DATABASE: ${DATABASE_NAME:-projetphp_livrable_epsi_bdd}
      MARIADB_USER: ${DATABASE_USER:-projetphp_livrable_epsi}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3310:3306"
    volumes:
      - db_data_prod:/var/lib/mysql

volumes:
  db_data_prod:
    driver: local
